# ตั้งค่า H2 Database in memory 
# Code ในการ Run H2 Database 
# http://localhost:9000/h2-console ->  JDBC URL ใส่ค่าเป็น jdbc:h2:mem:testdb
spring:
  jpa:
    show-sql: false
  h2:
    console:
      enabled: true

team24:
  app:
    jwtSecret: Team24SecreteKey
    jwtExpirationMs: 86400000

server:
  port: 9000
